#!/bin/sh

# stty -icanon -echo
# key="$(dd bs=1 count=1 2>/dev/null)"
# stty icanon echo

# printf "%s\n" "$key"

mime(){ file -bi "$1"; }
handle(){
	mime=$(mime "$1")
	case "$mime" in
		inode/directory*)
			cd "$1" && pwd
			;;
		image/*)
			./imgView "$1" "$1"
			;;
		video/*)
			ffplay "$1" >/dev/null 2>&1
			;;
		audio/*)
			ffmpeg "$1" >/dev/null 2>&1
			;;
		*)
			printf "[%s]: not supported\n" "$mime"
			;;
	esac
}

[ -z "$1" ] && $0 "-h" && exit 1

case $1 in
	-h)
		printf "%s -[hv]\n" "$0"
		exit 0
	;;
	-v)
		printf "0.0\n"
		exit 0
	;;
	*)
		[ ! -f "$1" ] && [ ! -d "$1" ] && printf "file: %s was not found\n" "$1" && exit 1
		handle "$1"
		exit 0
	;;
esac
