#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
pgrep -x sxhkd > /dev/null || sxhkd &

(wal -i ~/Immagini/wallpapers/Good/Cercare/10.jpg && bspc config normal_border_color $(xrdb -query | sed -n '1p' | awk '{print $2}') && bspc config focused_border_color $(xrdb -query | sed -n '3p' | awk '{print $2}') && pgrep -x polybar > /dev/null || polybar -r main &) &

bspc config border_width 3
bspc config window_gap 9

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
